jobs:
  - job: Deploy
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: PowerShell@2
        displayName: Delta Execute
        inputs:
          filePath: "deploy/Delta.ps1"
      - task: ArchiveFiles@2
        displayName: "Archive deltafiles"
        inputs:
          rootFolderOrFile: "deploysource"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "deploysource_$(Build.BuildId).zip"
          replaceExistingArchive: true
      - task: ArchiveFiles@2
        displayName: "Archive deployfiles"
        inputs:
          rootFolderOrFile: "deploy"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "deploy_$(Build.BuildId).zip"
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Delta"
        inputs:
          PathtoPublish: "deploysource_$(Build.BuildId).zip"
          ArtifactName: "deploysource_artifact"
          publishLocation: "Container"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Deploy"
        inputs:
          PathtoPublish: "deploy_$(Build.BuildId).zip"
          ArtifactName: "deploy_artifact"
          publishLocation: "Container"
